languages: ["de", "en"]
name: Freifunk KÃ¶ln, Bonn und Umgebung
wikilink: //kbu.freifunk.net/wiki/
exclude: [vendor]
maplink: http://map.kbu.freifunk.net/geomap.html
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data","smart"]
include: ['.htaccess']
highlighter: 'pygments'
image:
    source: _assets/images/original
    output: generated
    presets:
        medium:
            width: 300
            height: 260
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts


baseurl: ""
permalink: /:year/:month/:title/
